#!/bin/bash

# Build a release tarball from source.
# Usage:
#   util/prepare_release -r <revision>
# Resulting tarball will reside in dist/

REVISION=HEAD
while getopts "r:" OPTION; do
    case ${OPTION} in
        r) REVISION="${OPTARG}"
    esac
done

PYTHON=${PYTHON:-python}

[ -d dist ] || mkdir dist
TMPDEST=$(mktemp -d --tmpdir udiskie-release-XXXXXXXX)

git archive --format=tar "${REVISION}" | tar -x -C "${TMPDEST}"
git log "${REVISION}" > "${TMPDEST}/CHANGES"

pushd "${TMPDEST}"
mv README.rst README
VERSION=$(${PYTHON} setup.py --version)
${PYTHON} setup.py sdist
popd

cp "${TMPDEST}/dist/udiskie-tray-${VERSION}.tar.gz" dist/

rm -rf "${TMPDEST}"
